name: "Commit and Push"
description: "Commit and push changes to the repository"
inputs:
  branch:
    description: "Branch to commit and push to"
    required: false
    default: "master"
  message:
    description: "Message for the commit"
    required: true
  repository:
    description: "Git repository URL"
    required: true
  ssh-host:
    description: "SSH host for the Git repository"
    required: true
  ssh-key:
    description: "SSH private key for pushing to the Git repository"
    required: true
  ssh-port:
    description: "SSH port for the Git repository"
    required: false
    default: "22"
  ssh-user:
    description: "SSH user for the Git repository"
    required: false
    default: "git"
runs:
  using: "composite"
  steps:
    - name: 🖌 Git Commit
      shell: bash
      env:
        COMMIT_MESSAGE: ${{ inputs.message }}
      run: |
        git config user.name gitea-actions
        git config user.email teabot@gitea.io
        git commit -m "$COMMIT_MESSAGE [skip ci]"

    - name: 🚀 Git Push
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{ inputs.ssh-key }}
        SSH_HOST: ${{ inputs.ssh-host }}
        SSH_PORT: ${{ inputs.ssh-port }}
        SSH_USER: ${{ inputs.ssh-user }}
        REPOSITORY: ${{ inputs.repository }}
        BRANCH: ${{ inputs.branch }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p "$SSH_PORT" "$SSH_HOST" >> ~/.ssh/known_hosts 2>/dev/null
        git remote set-url origin "ssh://$SSH_USER@$SSH_HOST:$SSH_PORT/$REPOSITORY.git"
        git push origin "HEAD:refs/heads/$BRANCH"
