name: "Setup Yarn"
description: "Setup Node.js and install dependencies using Yarn"
inputs:
  node-version:
    description: "The version of Node.js to use"
    required: true
  registry-token:
    description: "The token to authenticate with the CompanyOfCube registry"
    required: false
runs:
  using: "composite"
  steps:
    - name: ⚙ Enable Corepack
      run: corepack enable

    - name: ⚙ Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn

    - name: 🔑 Authenticate with registry
      if: ${{ inputs.registry-token != '' }}
      shell: bash
      run: yarn config set npmScopes.companyofcube.npmAuthToken ${{ inputs.registry-token }}

    - name: 📦 Install dependencies
      shell: bash
      run: yarn install --immutable
